### ISSUE TITLE
Combine this repository with starfish

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/slicedimage#49]
sptx-format should move into starfish.

**Comment by ttung** [comment]
I don't know if github has a repo merging function, but if it doesn't, you should consider doing a proper git merge to preserve history.

**Comment by ambrosejcarr** [comment]
You sound like you know how to do this.

**Comment by joshmoore** [comment]
Currently working on https://github.com/joshmoore/build-starfish/ as a suggestion of how this could work.

**Comment by ttung** [comment]
I don't think this is going to happen.
